import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error("Supabase credentials not configured");
    }

    const { articleId, content } = await req.json();

    if (!articleId || !content) {
      throw new Error("articleId and content are required");
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    console.log(`Generating summary for article ${articleId}...`);

    // Call Lovable AI to generate structured summary
    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          {
            role: "system",
            content: `You are an expert news analyst and summarizer. Your job is to distill complex articles into clear, actionable insights for busy professionals.

Generate a comprehensive summary with the following structure:
1. Executive Summary (2-3 sentences capturing the essence)
2. Key Points (3-5 bullet points of the most important facts)
3. Analysis (2-3 sentences on implications and context)
4. Takeaways (2-3 actionable insights or things to watch)

Be concise but thorough. Focus on what matters to decision-makers.`,
          },
          {
            role: "user",
            content: `Please analyze and summarize this article:\n\n${content.slice(0, 8000)}`,
          },
        ],
        tools: [
          {
            type: "function",
            function: {
              name: "create_summary",
              description: "Create a structured article summary",
              parameters: {
                type: "object",
                properties: {
                  executive_summary: {
                    type: "string",
                    description: "2-3 sentence executive summary",
                  },
                  key_points: {
                    type: "array",
                    items: { type: "string" },
                    description: "3-5 key points as bullet points",
                  },
                  analysis: {
                    type: "string",
                    description: "2-3 sentences of context and implications",
                  },
                  takeaways: {
                    type: "array",
                    items: { type: "string" },
                    description: "2-3 actionable takeaways",
                  },
                },
                required: ["executive_summary", "key_points", "analysis", "takeaways"],
                additionalProperties: false,
              },
            },
          },
        ],
        tool_choice: { type: "function", function: { name: "create_summary" } },
      }),
    });

    if (!aiResponse.ok) {
      if (aiResponse.status === 429) {
        throw new Error("Rate limit exceeded. Please try again later.");
      }
      if (aiResponse.status === 402) {
        throw new Error("AI credits exhausted. Please add credits to continue.");
      }
      const errorText = await aiResponse.text();
      throw new Error(`AI API error [${aiResponse.status}]: ${errorText}`);
    }

    const aiData = await aiResponse.json();
    const toolCall = aiData.choices?.[0]?.message?.tool_calls?.[0];
    
    if (!toolCall?.function?.arguments) {
      throw new Error("No summary generated by AI");
    }

    const summary = JSON.parse(toolCall.function.arguments);

    console.log("Summary generated:", summary.executive_summary.slice(0, 100) + "...");

    // Insert summary
    const { error: summaryError } = await supabase
      .from("summaries")
      .upsert({
        article_id: articleId,
        executive_summary: summary.executive_summary,
        key_points: summary.key_points,
        analysis: summary.analysis,
        takeaways: summary.takeaways,
        model_used: "google/gemini-3-flash-preview",
        confidence_score: 0.85,
      }, {
        onConflict: "article_id",
      });

    if (summaryError) {
      throw new Error(`Failed to save summary: ${summaryError.message}`);
    }

    // Update article status to published
    const { error: updateError } = await supabase
      .from("articles")
      .update({
        status: "published",
        summary: summary.executive_summary,
        updated_at: new Date().toISOString(),
      })
      .eq("id", articleId);

    if (updateError) {
      throw new Error(`Failed to update article: ${updateError.message}`);
    }

    console.log(`Article ${articleId} summarized and published`);

    return new Response(
      JSON.stringify({
        success: true,
        articleId,
        summary: {
          executive_summary: summary.executive_summary,
          key_points_count: summary.key_points.length,
          takeaways_count: summary.takeaways.length,
        },
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Summarization error:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
