import { ExternalLink } from 'lucide-react';
import { motion } from 'framer-motion';

interface SourceCreditsProps {
  author: string;
  publication: string;
  sourceUrl: string;
}

export const SourceCredits = ({ author, publication, sourceUrl }: SourceCreditsProps) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.3 }}
      className="border-2 border-border-strong bg-secondary/30 p-6"
    >
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div className="min-w-0 flex-1">
          <h3 className="terminal-text font-medium text-foreground mb-3">
            Source & Credits
          </h3>
          <div className="space-y-2">
            <p className="text-sm">
              <span className="text-muted-foreground">Author:</span>{' '}
              <span className="font-medium break-words">{author}</span>
            </p>
            <p className="text-sm">
              <span className="text-muted-foreground">Publication:</span>{' '}
              <span className="font-medium break-words">{publication}</span>
            </p>
          </div>
        </div>
        <a
          href={sourceUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center gap-2 px-4 py-2 bg-foreground text-background font-mono text-xs uppercase tracking-wider hover:opacity-90 transition-opacity flex-shrink-0 w-full sm:w-auto"
        >
          Read Original
          <ExternalLink className="w-3 h-3" />
        </a>
      </div>
      <p className="text-xs text-muted-foreground mt-4 pt-4 border-t border-border">
        This summary was generated by AI. We encourage readers to visit the original source for the complete article.
      </p>
    </motion.div>
  );
};
